### ISSUE TITLE
App icon is the same as Polls

### ISSUE THREAD

**Issue by marcelklehr** [affan98/forms#13]
Currently the app icon is the same as the one for polls, which is confusing, I think.

**Comment by JimmyKater** [comment]
+1

**Comment by jancborchardt** [comment]
Created a new icon, what do you think?
![forms icon new](https://user-images.githubusercontent.com/925062/59275421-953a0c00-8c5c-11e9-9fd7-79e4eb2d0c7e.png)
![Forms icon new](https://user-images.githubusercontent.com/925062/59275419-94a17580-8c5c-11e9-93b4-be8a54c0ebf1.png)

@juliushaertl this app still has all these files like: app.png, favicon.ico, favicon.png, favicon.svg, favicon-mask.svg, favicon-touch.png – are they still needed, or aren’t they autogenerated meanwhile?

**Comment by juliushaertl** [comment]
@jancborchardt It still makes sense to keep those imo, since they are the fallbacks for setups where the imagemagick setup is not configured properly to generate the icons.

**Comment by jancborchardt** [comment]
Pull request open at https://github.com/affan98/forms/pull/16, please review :)
