### ISSUE TITLE
Add Forms to Transifex

### ISSUE THREAD

**Issue by rkaraba** [affan98/forms#2]
Thank you for creating this app.
Internationalization of Forms would be nice future.
Please add Forms to [Transifex](https://www.transifex.com/nextcloud/nextcloud/dashboard/) so users can help translate it.

**Comment by jancborchardt** [comment]
Yes! :) @MorrisJobke @rullzer can anyone help with this?

**Comment by MorrisJobke** [comment]
The config files look already good. Could you add @nextcloud-bot as collaborator here? Then it can push the translations to your app 😉

**Comment by MorrisJobke** [comment]
There it is: https://www.transifex.com/nextcloud/nextcloud/forms/

**Comment by MorrisJobke** [comment]
And there is the first batch: https://github.com/affan98/forms/commit/b8a7caa31b39c2c55988a5eb2457f676260aec27
